name: Build Flutter Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Prepare Project and Clean
        run: |
          if (Test-Path "windows") { Remove-Item -Recurse -Force "windows" }
          
          # PERBAIKAN VERSI MEDIA_KIT_LIBS_VIDEO KE ^1.0.7 SESUAI PERMINTAAN SISTEM
          $pubspec = @"
          name: pengumuman_pro
          description: Professional Broadcast System
          publish_to: 'none'
          version: 1.0.0+1
          environment:
            sdk: '>=3.0.0 <4.0.0'
          dependencies:
            flutter:
              sdk: flutter
            desktop_multi_window: ^0.2.0
            file_picker: ^8.0.0
            media_kit: ^1.1.11
            media_kit_video: ^1.2.5
            media_kit_libs_video: ^1.0.7
            window_manager: ^0.3.8
            shared_preferences: ^2.2.2
          flutter:
            uses-material-design: true
          "@
          Set-Content -Path pubspec.yaml -Value $pubspec
          
          flutter create --project-name pengumuman_pro --platforms=windows .
          flutter pub get
        shell: powershell

      - name: Inject Multi-Window C++
        run: |
          $file = "windows\runner\flutter_window.cpp"
          $content = Get-Content -Path $file -Raw
          $content = $content -replace '#include "flutter/generated_plugin_registrant.h"', "#include `"flutter/generated_plugin_registrant.h`"`n#include <desktop_multi_window/desktop_multi_window_plugin.h>"
          $callback = "RegisterPlugins(flutter_controller_->engine());`n  DesktopMultiWindowSetWindowCreatedCallback([](void *controller) {`n    auto *flutter_view_controller = reinterpret_cast<flutter::FlutterViewController*>(controller);`n    RegisterPlugins(flutter_view_controller->engine());`n  });"
          $content = $content -replace 'RegisterPlugins\(flutter_controller_->engine\(\)\);', $callback
          Set-Content -Path $file -Value $content
        shell: powershell

      - name: Build Windows App
        run: flutter build windows --release

      - name: Zip Build Output
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath Software-Pengumuman-Windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: software-pengumuman-flutter
          path: Software-Pengumuman-Windows.zip
